include $(TOPDIR)/rules.mk

PKG_VERSION:=3.6.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI Support for rtp2httpd
LUCI_DEPENDS:=+rtp2httpd

PKG_MAINTAINER:=Stackie Jia <jsq2627@gmail.com>
PKG_LICENSE:=GPL-2.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
