#!/bin/sh

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vlmcsd[-1]
	add ucitrack vlmcsd
	set ucitrack.@vlmcsd[-1].init=vlmcsd
	commit ucitrack
EOF
}

rm -rf /tmp/luci-indexcache*
exit 0
